# Generated by Django 3.2.13 on 2023-01-05 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('subjects', models.JSONField()),
                ('subject_acc_class', models.JSONField()),
                ('grades_taught', models.JSONField()),
            ],
        ),
    ]
