# Generated by Django 3.2.13 on 2023-01-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='grades_taught',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
    ]
