# Generated by Django 3.2.13 on 2023-01-19 05:17

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20230119_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(15, 0)),
        ),
        migrations.AddField(
            model_name='timetable',
            name='len_per_period',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lunch_period',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='timetable',
            name='no_of_teachers',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='timetable',
            name='periods',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='timetable',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('39f1662d-806f-496e-b0da-43f708fad297')),
        ),
    ]
