# Generated by Django 4.1.5 on 2023-01-22 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20230119_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_acc_class',
        ),
        migrations.AddField(
            model_name='teacher',
            name='grades_taught',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='None', max_length=256),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teachers',
            field=models.ManyToManyField(to='timetable.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='Teach', max_length=256),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1cc011fe-c84b-449f-8bd1-f38134c7040e'), unique=True),
        ),
    ]
