# Generated by Django 4.1.5 on 2023-01-22 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_teacher_subject_acc_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9d10eecf-855f-4d7d-bce3-de0de330609b'), unique=True),
        ),
    ]
