# Generated by Django 4.1.5 on 2023-01-30 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_timetable_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c2a877fa-b2aa-4655-92d1-8f8dfe0bcbc4'), unique=True),
        ),
    ]
