# Generated by Django 4.1.5 on 2023-01-30 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_timetable_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='timetable',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ee425bea-2237-4c66-90d4-5d8d155a20dc'), unique=True),
        ),
    ]
