# Generated by Django 4.1.5 on 2023-01-30 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_timetable_timetable_alter_timetable_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='used_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d26a0bc6-1234-4e64-be7f-a258518f377d'), unique=True),
        ),
    ]
