# Generated by Django 3.2.13 on 2023-01-30 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_timetable_used_once_alter_timetable_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('da36e83a-500a-4cc5-9f61-f7583cebfa70'), unique=True),
        ),
    ]
