# Generated by Django 3.2.13 on 2023-01-31 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_timetable_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
