# Generated by Django 4.1.5 on 2023-01-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_remove_timetable_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='timings',
            field=models.JSONField(null=True),
        ),
    ]
